# Generated by Django 3.2.11 on 2022-01-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(verbose_name='sana')),
            ],
        ),
        migrations.AlterModelOptions(
            name='talaba',
            options={'verbose_name': 'Talaba', 'verbose_name_plural': 'Talabalar'},
        ),
        migrations.AddField(
            model_name='talaba',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
